Feature: adds prometheus metrics and prometheus to the helm chart
inspr/core-legacy pull request #109
Opened 2021-08-06 23:48 UTC by ptcar2009

# Description

Kind:

Section:

Summary:

## Changelog

> List the main points of change

## Pay attention to

> Important parts of the code that require special attention

2021-08-25 12:27 UTC, nicholaspcr approved these changes

2021-08-25 13:35 UTC, lucasABLima commented on Makefile
> +## builds inprov to the bin directori
## builds inprov to the bin directory

2021-08-25 13:38 UTC, lucasABLima commented on pkg/rest/request/request.go
> -	defer req.Body.Close()
Wouldn't this change cause the same memory leak that we have previously?

2021-08-25 17:26 UTC, ptcar2009 commented on pkg/rest/request/request.go
> -	defer req.Body.Close()
The request body is closed automatically, the issue is with the response body. You can check with @nicholaspcr , he got the changes and what needed to be changed. This was already tested and doesn't interfere with performance, and is also more idiomatic

2021-08-25 18:02 UTC, nicholaspcr commented on pkg/rest/request/request.go
> -	defer req.Body.Close()
I assumed that the one opening the request should be responsible for closing it, but if you tested and the memory hasn't increased then maybe my knowledge about it might be flawed.

Will read the doc again to confirm it

2021-08-25 18:39 UTC, nicholaspcr commented
@ptcar2009  Forgot to add it here when i was reading about the PR.

Mate put a description of what exactly was done, from what i could gather there is the prometheus metrics and helm chart but in here is also included the makefile that you talked with me.

Ideally would be nice for each one of these three things to be on their own PR. That way would be a lot easier to review what's being added to the repo.

Also there are some tests that are broken

2021-08-30 15:16 UTC, luiz-couto commented on CHANGELOG.md
> +### #101 Fix | adds routine for collecting kafka events
I didnt get this changelo. Also, add the changelog of this PR

2021-08-30 15:18 UTC, luiz-couto requested changes
For me its fine. Just add the correct changelog to it

2021-08-30 16:34 UTC, nicholaspcr approved these changes

2021-08-30 17:24 UTC, LucasStarlingdePaulaSalles approved these changes

2021-08-31 11:41 UTC, lucasABLima approved these changes

2021-08-31 12:05 UTC, luiz-couto approved these changes

2021-08-31 12:14 UTC, merged