Story/core 580 | Create Route structure on the Node definition
inspr/core-legacy pull request #135
Opened 2021-09-21 12:57 UTC by lucasABLima

# Description

Kind: Feature

Section: Pkg/meta

Summary: Created the route structure and its connection structure. 
Add route to node structure and connection to app structure.

## Changelog
* created Route structure on the `pkg/meta`
* added route structure to the NodeSpec structure
* added route connection map to the AppSpec structure

2021-09-21 13:52 UTC, LucasStarlingdePaulaSalles requested changes

2021-09-21 13:52 UTC, LucasStarlingdePaulaSalles commented on pkg/meta/route.go
> +// which is a http request address related to the endpoints
Replace second line: Endpoints is a list of allowed endpoints on regarding the route

2021-09-21 14:11 UTC, lucasABLima commented on pkg/meta/route.go
> +// which is a http request address related to the endpoints
Done

2021-09-21 14:46 UTC, LucasStarlingdePaulaSalles approved these changes

2021-09-21 18:43 UTC, ptcar2009 commented
What's gonna be the overall design here?

2021-09-22 17:12 UTC, luiz-couto approved these changes

2021-09-23 11:51 UTC, merged