fix: remove gitlab references
inspr/core-legacy pull request #20
Opened 2021-04-18 20:02 UTC by brenordr

# Description

Remove references to Gitlab

Kind: Fix

Section:

Summary:

Issue link:

## Changelog

> List the main points of change

## Pay attention to

> Important parts of the code that require special attention

2021-04-19 11:46 UTC, nicholaspcr approved these changes

2021-04-19 17:42 UTC, luiz-couto approved these changes

2021-04-20 16:01 UTC, ptcar2009 requested changes

2021-04-20 16:01 UTC, ptcar2009 commented on docs/cli_install.md
> +To get other Inspr CLI versions, download the binary file from the GitHub repository [here](https://github.com/inspr/inspr/-/releases).
I think this link has to be changed.

2021-04-21 19:52 UTC, brenordr commented on docs/cli_install.md
> +To get other Inspr CLI versions, download the binary file from the GitHub repository [here](https://github.com/inspr/inspr/-/releases).
@ptcar2009 Why?

2021-04-21 20:11 UTC, ptcar2009 commented on docs/cli_install.md
> +To get other Inspr CLI versions, download the binary file from the GitHub repository [here](https://github.com/inspr/inspr/-/releases).
I think there is no hyphen

2021-04-21 22:58 UTC, brenordr reviewed
Fixes applied with success

2021-04-21 22:58 UTC, brenordr commented on docs/cli_install.md
> +To get other Inspr CLI versions, download the binary file from the GitHub repository [here](https://github.com/inspr/inspr/-/releases).
done

2021-04-22 14:51 UTC, ptcar2009 approved these changes
LGTM

2021-04-22 15:10 UTC, merged