Issue CORE-307 | Adds token to the controller client
inspr/core-legacy pull request #24
Opened 2021-04-19 19:50 UTC by ptcar2009

# Description

Kind: feature

Section: controller

Summary: adds token to the controller client

Issue link: https://inspr.atlassian.net/browse/CORE-307

## Changelog
- adds a method to the controller client that sets headers
-  adds a method that sets the token directly

## Pay attention to

- syntax on token adding

2021-04-20 11:50 UTC, LucasStarlingdePaulaSalles requested changes

2021-04-20 11:50 UTC, LucasStarlingdePaulaSalles commented on pkg/rest/request/builder.go
> +func (cb *ClientBuilder) Token(token []byte) *ClientBuilder {
Shouldn't this be called on the cli client?

2021-04-20 11:50 UTC, franciscobonand requested changes
Shouldn't the new Token builder created on pkg/rest/request/... be applied to the cli controller instantiation in the method "setGlobalClient" of cliutils?

2021-04-21 18:10 UTC, franciscobonand approved these changes
The controller client change was a pretty good ideia

2021-04-22 12:57 UTC, LucasStarlingdePaulaSalles approved these changes

2021-04-22 13:01 UTC, merged