Issue CORE-332 | authentication field creation and injection
inspr/core-legacy pull request #27
Opened 2021-04-20 19:14 UTC by ptcar2009

# Description

Kind: feature

Section: metadata, dapp controller

Summary: creates a field for auth and injects it on dapp creation

Issue link: https://inspr.atlassian.net/browse/CORE-332?atlOrigin=eyJpIjoiNGQ1ODJmYTc4OTA0NDgxOGIyOGU4NmUwYWExYjMwYTkiLCJwIjoiaiJ9

## Changelog

- creates the field on meta
- injects on dapp creation
- tests uid injection

2021-04-20 19:32 UTC, franciscobonand requested changes
In `cmd/insprd/memory/tree/manager.go` it might be a good idea to instantiate the new Auth field of the root dApp as being `nil` in the function `newTreeMemory()`

2021-04-20 19:32 UTC, franciscobonand commented on pkg/meta/dapp.go
> +	Permissions utils.StringArray `yaml:"permissions"  json:"permissions"`
Wouldn't the permissions be a map? Something like:
```yaml
- create:dapp
- delete:channels7
```

2021-04-22 12:01 UTC, franciscobonand commented on pkg/meta/dapp.go
> +	Permissions utils.StringArray `yaml:"permissions"  json:"permissions"`
Just saw CORE-336 description and I was wrong, mb

2021-04-22 14:23 UTC, franciscobonand approved these changes

2021-04-22 14:24 UTC, luiz-couto approved these changes

2021-04-22 14:43 UTC, merged