Tech CORE-359 | renaming the ChannelType struct to be Type
inspr/core-legacy pull request #46
Opened 2021-05-06 15:23 UTC by nicholaspcr

# Description

Kind: Technical Dependency

Section: meta pkg and all it entails

Summary: Renaming the ChannelType structure to better fit the upcoming new features

## Changelog

> List the main points of change

The process of change was to simply find of occurrences of:
-  `Channel_Type` and replace it with `Type`
-  `ChannelType` and replace it with `Type`
-  `Channel Type` and replace it with `Type`

## Pay attention to

> Important parts of the code that require special attention
> - there are still places where the `Type` is abreviated as `ct`, it made sense for me since is when the type is treated as a ChannelType
> - might have had some place that it might have been better to leave as ChannelType, would like the opinion of who is revising

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles requested changes

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on build/helm/templates/ingress.yaml
> +          - path: /Types
lower case

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/apply_channel_type.go
> +		Type, err := utils.YamlToType(data)
Capitalized variable

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/delete.go
> +		WithExample("Delete Type from a custom scope", "delete ctypes <ctypename> --scope app1.app2").
Captalization against pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/delete_test.go
> +			name:           "Should delete the Type and return the diff",
capitalization in message

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/describe.go
> +		WithExample("Display the state of the given Type by the path", "describe ctypes app1.app2.hello_world").
Capitalization on messages

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/describe.go
> +	Type, err := client.Types().Get(context.Background(), path, ctName)
capitalized variable

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/describe_test.go
> +			name:           "Should describe the Type state",
capitalization on test name, different from pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/cli/get.go
> +		WithExample("Get Types from a custom scope", "get ctypes --scope app1.app2").
Capitalization on messages

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/inspr/main.go
> +		Kind:       "Type",
Capitalization on cli kind

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/fake/alias.go
> +			Message("Type %s not found", context).
Capitalization on message

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/fake/alias.go
> +			Message("Type %s not found", context).
Capitalization on message

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/fake/mem_manager.go
> +	Type    Types
Capitalization attribute

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/tree/channel.go
> +	Type := parentApp.Spec.Types[channel.Spec.Type]
capitalized variable

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/tree/dapp_utils.go
> +				return false, "invalid channel: using non-existent Type;"
Capitalization on message

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on cmd/insprd/memory/tree/dapp_utils_test.go
> +			name: "invalid channel: using non-existent Type",
Capitalization on message

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr-delete-ctypes.1
> +  # Delete Type from a custom scope
ctypename acronym, although I think this is autio generated

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr-describe-ctypes.1
>   inspr describe ctypes app1.app2.hello\_world
ctype acronym

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr-get-ctypes.1
>   inspr get ctypes \-\-scope app1.app2
ctype

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_delete.md
> +* [inspr delete ctypes](inspr_delete_ctypes.md)	 - Delete Types from context
Capitalization out of pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_delete_ctypes.md
>   inspr delete ctypes <ctypename> --scope app1.app2
ctype

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_describe.md
> +* [inspr describe ctypes](inspr_describe_ctypes.md)	 - Retrieves the full state of the Type from a given namespace
Capitalization out of pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_describe_ctypes.md
>  ## inspr describe ctypes
ctype all over file

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_get.md
> +* [inspr get ctypes](inspr_get_ctypes.md)	 - Get Types from context
Capitalization out of pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/cli/inspr_get_ctypes.md
> +  # Get Types from a custom scope
Capitalization out of pattern, and ctype on file

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/pubsub.md
> +kind: Type
Capitalization out of pattern, on this case it is acctually important because the kind of the yaml should be lower case

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/workspace_init.md
> +kind: Type
Capitalization out of pattern, yaml kind again

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/yamls/index.md
> +  Types:
Capitalization out of pattern, would cause problems unmarshaling

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on docs/yamls/type.md
> +kind: Type
Capitalization out of pattern, yaml kind

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on examples/k8s_op_demo/README.md
> +This demo creates channels/Types/dApps in memory an then applies these creations inside the running Cluster.
Capitalization out of pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on examples/k8s_op_demo/README.md
> +If desired, the main.go in this folder can be edited to create channels/Types/dApps with different information. Be advised that by doing so, it is necessary to rebuild and push the Docker Image.
Capitalization out of pattern

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on examples/multi_channel_demo/yamls/01.cht.yaml
> +kind: Type
Capitalization out of pattern, yaml type

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on examples/primes/yamls/channel_types/ct1.yaml
> +kind: "type"
this sometimes has quotations, sometimes not. does it change anything? I think not but i'm not entirely sure

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/api/controllers/routes.go
> +	s.Mux.Handle("/Types", rest.HandleCRUD(cthandler))
Capitalization out of pattern, endpoint

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/api/controllers/routes_test.go
> +			name: "Types",
Capitalization out of pattern, endpoint. I think if you fix the endpoint name you have to change this as well

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/api/handlers/type_handler.go
> +		ctype, err := cth.Memory.Root().Types().Get(scope, data.TypeName)
ctype acronym

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/api/models/channel_type.go
> +	TypeName string `json:"tname"`
I think the json var should be called the same thing as the struct one, only lowercase. typename.

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/controller/client/type.go
> +func (ctc *TypeClient) Get(ctx context.Context, scope string, name string) (*meta.Type, error) {
ctc acronyms on file.

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/controller/client/type.go
> +	ctdi := models.TypeQueryDI{
ctdi acronym, also frequent on file

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/meta/utils/format.go
> +	Type := gotree.New(ct.Meta.Name)
Capitalization out of pattern, varible

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/meta/utils/parser/type_yaml.go
> +	Type := meta.Type{
Capitalization out of pattern, variable

2021-05-10 19:08 UTC, LucasStarlingdePaulaSalles commented on pkg/meta/utils/parser/type_yaml_test.go
> +	TypeFile = "type_yaml_test.yaml"
Capitalization out of pattern, constant name

2021-05-11 14:33 UTC, LucasStarlingdePaulaSalles approved these changes

2021-05-11 15:56 UTC, luiz-couto requested changes

2021-05-11 15:56 UTC, luiz-couto commented on cmd/inspr/cli/describe.go
> +		WithDescription("Retrieves the full state of the ctype from a given namespace").
change "ctype" to "type" (everywhere)

2021-05-11 15:56 UTC, luiz-couto commented on cmd/insprd/memory/fake/mem_manager.go
> +	itype   Types // inspr type
itype to insprType

2021-05-11 15:56 UTC, luiz-couto commented on cmd/insprd/memory/fake/type.go
> +	Types map[string]*meta.Type
"Types" to "types"

2021-05-11 15:56 UTC, luiz-couto commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Create(context string, ct *meta.Type) error {
"ctm" -> tmm
"ct" -> insprType

2021-05-11 15:56 UTC, luiz-couto commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Get(context string, ctName string) (*meta.Type, error) {
ctm -> tmm
ctName -> typeName

2021-05-11 15:56 UTC, luiz-couto commented on cmd/insprd/memory/tree/types.go
> +		zap.String("ctype", ctName),
here

2021-05-11 15:56 UTC, luiz-couto commented on examples/master_demo/main.go
> +	utils.PrintTypeTree(cType, os.Stdout)
heree

2021-05-11 15:56 UTC, luiz-couto commented on pkg/meta/utils/format.go
> +func PrintTypeTree(t *meta.Type, out io.Writer) {
t -> insprType

2021-05-11 16:11 UTC, franciscobonand requested changes

2021-05-11 16:11 UTC, franciscobonand commented on cmd/inspr/cli/describe.go
> +		WithExample("Display the state of the given ctype by the path", "describe ctypes app1.app2.hello_world").
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on cmd/inspr/cli/get.go
> +		WithExample("gets ctypes from cluster", "get ct --scope <scope>").
ctypes -> types

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/fake/mem_manager.go
> +	itype   Types // inspr type
itype -> insprType

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +			zap.String("ctype", ct.Meta.Name))
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Create(context string, ct *meta.Type) error {
ct -> type

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		zap.String("channel", ct.Meta.Name),
"channel" doesn't make sense anymore

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		newError := ierrors.NewError().InnerError(err).InvalidChannel().
The error `.InvalidChannel()` isn't correctly placed here anymore

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Get(context string, ctName string) (*meta.Type, error) {
ctName -> typeName

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		zap.String("ctype", ctName),
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Delete(context string, ctName string) error {
ctName -> typeName

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +			Message("Type cannot be deleted as it is being used by other channels").
"... is being used by other structures"

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +func (ctm *TypeMemoryManager) Update(context string, ct *meta.Type) error {
ct -> type

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		zap.String("channel", ct.Meta.Name),
"channel" doesn't make sense anymore

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +func (amm *TypeRootGetter) Get(context string, ctName string) (*meta.Type, error) {
ctName -> typeName

2021-05-11 16:11 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		zap.String("ctype", ctName),
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on examples/primes/yamls/channel_types/ct1.yaml
> +kind: "type"
As long as its a string like that, I believe it doesn't matter

2021-05-11 16:11 UTC, franciscobonand commented on pkg/api/handlers/type_handler.go
> +				zap.String("ctype", data.Type.Meta.Name),
Channel Type -> Type  
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on pkg/api/handlers/type_handler.go
> +				zap.String("ctype", data.Type.Meta.Name),
Channel Type -> Type
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on pkg/api/handlers/type_handler.go
> +				zap.String("ctype", data.TypeName),
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on pkg/auth/models.go
> +	DeleteAlias   string = "delete:alias"
ctype -> type

2021-05-11 16:11 UTC, franciscobonand commented on pkg/meta/dapp.go
> +	Types    map[string]*Type    `yaml:"channeltypes,omitempty"   json:"channel_types"`
Tags are "channeltypes", should be "types"

2021-05-11 16:11 UTC, franciscobonand commented on pkg/meta/utils/format.go
> +			Types.Add(ctName)
The variable "Types" should be "types" to keep the pattern of variable declaration

2021-05-11 16:11 UTC, franciscobonand commented on pkg/meta/utils/testutils.go
> +	for _, ct := range app.Spec.Types {
ct -> type

2021-05-11 16:11 UTC, franciscobonand commented on pkg/rest/constants.go
> +	"types":    "ctype",
ctype -> type

2021-05-12 12:19 UTC, franciscobonand requested changes

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/delete.go
> +		WithExample("deletes type", "delete ct <type_name>").
Shouldn't this be "delete **t** <type_name>"?

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/delete.go
> +func deletetypes(_ context.Context, args []string) error {
I think it's better to change this func name to camel case, to maintain the project pattern

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/describe.go
>  		WithAliases([]string{"ct"}).
This alias should be "t", right?

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/get.go
> +		WithExample("gets types from cluster", "get ct --scope <scope>").
Shouldn't this be "get **t** <type_name>"?

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/get.go
> +func gettypes(_ context.Context) error {
I think it's better to change this func name to camel case, to maintain the project pattern

2021-05-12 12:19 UTC, franciscobonand commented on cmd/inspr/cli/get.go
> +func printtypes(app *meta.App, lines *[]string) {
Same func naming here

2021-05-12 12:19 UTC, franciscobonand commented on cmd/insprd/memory/tree/types.go
> +		zap.String("channel", insprType.Meta.Name),
Printing "channel" in this logger doesn't make sense anymore

2021-05-12 16:02 UTC, franciscobonand approved these changes

2021-05-12 16:03 UTC, luiz-couto approved these changes

2021-05-12 16:04 UTC, merged