Feature: adds pre-commit hook and hook wrapper
inspr/core-legacy pull request #51
Opened 2021-05-10 20:56 UTC by ptcar2009

# Description

Kind: feature

Section: git

Summary: creates a script for installing and updating git hooks for git

## Changelog
- feature:
	- creates a wrapper script for git hooks
	- creates a pre-commit script for linting files that are staged for committing
	- creates an installation script that creates symlinks for the hooks

## Pay attention to
A git hook is a script that runs on a given moment by `git`. It has to have a specific name and is run with proper arguments on a stage of the git pipeline. The architecture in this PR basically creates a folder that contains all hooks and creates symlinks to those hooks if they exist, while preserving the original hooks from the user for the repository. 

The only added hook for now is a pre-commit hook that lints staged files and fails the commit if the lint does not pass.

To install the hooks locally, run the `scripts/install-hooks.sh` script from the repository, and it should run automatically from then. (you need to have the `go` command PATH set on your `.bashrc` for it to work, otherwise it will not work properly, and you need `golint` installed and on your `bash` path)
> Important parts of the code that require special attention

2021-05-11 14:56 UTC, LucasStarlingdePaulaSalles approved these changes

2021-05-12 16:22 UTC, franciscobonand requested changes

2021-05-12 16:22 UTC, franciscobonand commented on scripts/hooks-wrapper.sh
> +    tracked_hooks/$(basename $0) "$@" || exit $?
"tracked_hooks" isn't the correct folder

2021-06-28 14:41 UTC, nicholaspcr approved these changes

2021-06-28 14:41 UTC, nicholaspcr commented on scripts/hooks/pre-commit
> +
might be interesting to use staticcheck as well, since it checks for a few more stuff than golint

2021-06-28 14:45 UTC, franciscobonand approved these changes

2021-06-29 13:21 UTC, nicholaspcr commented
After changing to statickcheck the `git commit` returned a error describing that the cached files were wrong. Since its not a priority to finish this, i will leave it as a draft and go back to the tasks of higher priority.

2021-07-06 11:41 UTC, franciscobonand approved these changes

2021-07-06 11:41 UTC, merged