Story/core 419 | Create Kafka sidecar Factory
inspr/core-legacy pull request #60
Opened 2021-05-18 16:56 UTC by nicholaspcr

# Description

Kind: story
Section: cmd/sidecars

Summary: create the function responsible for returning the type `SidecarFactory`, that is responsible for generating the sidecar deployment configuration for k8s.

## Changelog
> - created the `kafka.go` file in the sidecars pkg, that way it allows for each sidear to have their own file in the pkg
> - utils file was created with functions that are duplicated from the nodes pkg in the operators folder, since that will change later on i decided that for now it would be the best to leave in a separate file and whoever takes the task of integrating the changes will adapt as he deems necessary.

## Pay attention to
> - important to look at the `converter.go` of the operators pkg when seeing the files of this PR, since most configurations were created taking that file as a base.

2021-05-19 13:14 UTC, nicholaspcr commented
Missing the manual test in the cluster, previously tried to replace the k8s.container with a new one build from the `kafka sidecar factory` funcitons.

That lead to the error in which the port was getting the default empty value of zero, which means it couldn't read from the env_var. So before merging is imperative to test again and see it working.

2021-05-20 11:09 UTC, franciscobonand commented on cmd/sidecars/utils.go
> +func generateWritePort() int32 { return int32(0) }
Are these necessary?

2021-05-20 11:09 UTC, franciscobonand commented on cmd/sidecars/kafka.go
> +		},
This is the port used by the kafka-specific sidecar in the service that is deployed with a dApp, right?

2021-05-20 11:09 UTC, franciscobonand commented on cmd/sidecars/kafka.go
> +				InsprAppIDConfig(app),
What is this used for, in practice?

2021-05-20 14:41 UTC, LucasStarlingdePaulaSalles requested changes

2021-05-20 14:41 UTC, LucasStarlingdePaulaSalles commented on cmd/sidecars/kafka.go
> +	ports models.SidecarConnections
This shouldn't be in here, SidecarFactory should receive a SidecarConnection object separate from the kafka config. (this is because we will be using a port finder to determine these ports)

2021-05-20 14:41 UTC, LucasStarlingdePaulaSalles commented on cmd/sidecars/utils.go
> +func generateWritePort() int32 { return int32(0) }
I would prefer a single function that returns a SidecarConnections object, containign both a read and write ports.

2021-05-20 17:37 UTC, franciscobonand approved these changes

2021-05-21 11:17 UTC, luiz-couto approved these changes

2021-05-21 12:17 UTC, LucasStarlingdePaulaSalles approved these changes

2021-05-21 12:34 UTC, merged