Story/core 485
inspr/core-legacy pull request #86
Opened 2021-07-02 10:58 UTC by nicholaspcr

# Description

Kind: Story

Section: Docs/Yamls

Summary: Writting a documentation explaning the necessary steps to run insprd and uidp on minikube.

2021-07-02 17:44 UTC, franciscobonand requested changes
Here is the text with some grammar fixes. Please do review the code snippets (some of them didn't have proper commands as described by the phrase right above them, and I fear Typora might've broken some of them as well):  

# Minikube installation

For the purporse of testing Insprd locally we recommmend using [minikube](https://minikube.sigs.k8s.io/docs/start/).

Following this tutorial you will see the necessary steps to have one of the Inspr's examples running locally, more specifically the `ping pong` demonstration, but it will work for any other.

The requirements for this tutorial are:

- [Docker Hub account](https://hub.docker.com/)
- [Docker installed](https://www.docker.com/)
- [kubectl installed](https://kubernetes.io/docs/tasks/tools/)
- [Helm installed](https://helm.sh/)
- [insprctl installed](cli_install.md)
- [Skaffold installed](https://skaffold.dev/)

# Step by Step

## Setting up minikube

Initialize the cluster by running `minikube start` in your terminal.

Run `kubectl config get-contexts` to confirm that the currently selected cluster is minikube.

After this is set, run the commands below for setting up the permissions of the cluster created and to create the namespace `inspr-apps`.

```zsh
$ kubectl create clusterrolebinding --clusterrole admin --serviceaccount default:default defaultserviceaccount
$ kubectl create namespace inspr-apps
```

## Installation of Insprd and UID Provider

The process of installation involves adding a few Helm repositories and running `helm install`, the detailed process can be found [here](https://github.com/inspr/inspr/blob/a70654b967c26e30ba48e54596461e86646ab8ed/docs/helm_installation.md).

In short the process consists of the following commands:

### **Using Helm**

```zsh
$ helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
$ helm repo update
$ helm install ingress-nginx ingress-nginx/ingress-nginx
```

For confirmation that the service is up and running run the command below, it should be a service with the name `ingress-nginx-controller`.

```zsh
$ kubectl get service -A
```

## **Installing Insprd**

```zsh
$ helm repo add inspr https://inspr-charts.storage.googleapis.com/
$ helm repo update
$ helm install insprd inspr/insprd \
    --set insprdRepository=gcr.io/red-inspr/insprd:v0.1.0 \
    --set authRepository=gcr.io/red-inspr/authsvc:v0.1.0 \
    --set secretRepository=gcr.io/red-inspr/secretgen:v0.1.0 \
    --set lbsidecarImage=gcr.io/red-inspr/inspr/sidecar/lbsidecar:v0.1.0
```

## **Installing UID Provider**

With the `insprd` and its `auth-svc` installed we can now install Inspr's UID Provider. This can be done by running `skaffold` in the [github repository](https://github.com/inspr/inspr) that contains the necessary information (you should clone the repository to your local machine).

First we need to open an IP so we can make requests to our minikube services, this can be done by the commands below.

```zsh
# leave it open in another terminal
$ minikube tunnel
# get the ip in which you will be doing the request
$ minikube ip
```

With the IP in hand add the entry to your local `/etc/hosts` in the following format:

```
127.0.0.1       localhost
::1             localhost
$MINIKUBE_IP    inspr.com
```

### **Setting up environment variables**

Set the environment variable on your local machine to fit the URL set in the `/etc/hosts`

```zsh
export INPROV_PROVIDER_URL="http://inspr.com"
```

### Obtaining the auth-svc token

After setting up the IP of minikube, use `insprctl` to obtain the `adminToken` generated in its service creation.

```zsh
$ insprctl cluster init 1234567890
```

This will return a token in a similar format to:

```
❯ insprctl cluster init 1234567890
This is a root token for authentication within your insprd. This will not be generated again. Save it wisely.
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUwNjkyNzQsInBheWxvYWQiOnsidWlkIjoiIiwicGVybWlzc2lvbnMiOnsiIjpbImNyZWF0ZTp0b2tlbiJdfSwicmVmcmVzaCI6bnVsbCwicmVmcmVzaHVybCI6IiJ9fQ.IHewUCK1kGZ5OspsSr9q-yzasvYOvRbKK887PAa_iFrFkE088FkpbnyffG2z4MiuFxypGxALuZ9CVW9MtREJrQ
```

Alter the file `build/uidp_helm/values.yaml` in the repository you cloned, set the value of `adminToken` to be the one that you got from the `insprctl` command.

### **Installing Redis**

To install Redis in the cluster we need the YAML files that we can use to create the Service and Configmap.

In you terminal create the two necessary files by using the commands below.

```
# content of configmap yaml file named uidp-configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis
        image: redis:6.2.1-alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-cluster
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
# content of the service yaml file named uidp-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis-cluster
" > uidp-svc.yaml
```

Run the following commands

```zsh
kubectl apply -f uidp-configMap.yaml
kuebctl apply -f uidp-svc.yaml

# wait for the deployment of the 6 pods to be done
# you can check running `kubectl get pods`

# then run the following command
kubectl exec -it redis-cluster-0 -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379 ' | sed -e 's/ :6379/ 127.0.0.1:6379/')
```

### **Using Skaffold**

Now that the `adminToken` is set enter the root directory of the cloned repository and run the command `skaffold run --profile uidp`. This will install the UID Provider into the minikube cluster.

## **Deploying dApps**

### **Setting up permissions' account**

With everything ready for the creation of dApps in the minikube cluster we only need to create a user in our system, that can be done by using the `inprov` CLI. It can be installed by running the following command from within the cloned repository's root folder:

```zsh
go install ./cmd/uid_provider/inprov
```

First create a `create_user.yaml` by using the command below:

```
# content of the create_user.yaml
uid: minikube
password: "123"
permissions:
  "":
    - "create:token"

    - "create:dapp"
    - "create:channel"
    - "create:type"
    - "create:alias"

    - "get:dapp"
    - "get:channel"
    - "get:type"
    - "get:alias"

    - "update:dapp"
    - "update:channel"
    - "update:type"
    - "update:alias"

    - "delete:dapp"
    - "delete:channel"
    - "delete:type"
    - "delete:alias"
```

Run the following `i [...]

2021-07-02 17:44 UTC, franciscobonand commented on docs/minikube.md
> +```
This doesn't seem like a command

2021-07-02 17:44 UTC, franciscobonand commented on docs/minikube.md
> +" > uidp-svc.yaml
Shouldn't it start with `"`?

2021-07-02 17:44 UTC, franciscobonand commented on docs/minikube.md
> +```
This doesn't seem like a command

2021-07-05 16:15 UTC, franciscobonand requested changes

2021-07-05 16:15 UTC, franciscobonand commented on docs/minikube.md
> +- Skaffold installed
Make this links to each of the installation methods. In my previous review comment I put all the links there

2021-07-05 16:15 UTC, franciscobonand commented on docs/minikube.md
> +## Installation of the insprd and uidp
"Installation of Insprd and UID Provider"*

2021-07-05 16:15 UTC, franciscobonand commented on docs/minikube.md
> +## **Installing UIDP Provider**
"UID Provider"*

2021-07-05 16:15 UTC, franciscobonand commented on docs/minikube.md
> +With the `insprd` and its `auth-svc` installed we can now install the inspr's UIDP Provider. This can be done by running `skaffold` in the [github repository](https://github.com/inspr/inspr) that con
- Inspr* (with capital letter)  
- It's not "UIDP Provider", it's "UID Provider"

2021-07-05 16:15 UTC, franciscobonand commented on docs/minikube.md
> +Run the following commands to deploy dapps into your minikube cluster.
dApps*

2021-07-05 17:34 UTC, franciscobonand approved these changes

2021-07-06 11:16 UTC, LucasStarlingdePaulaSalles approved these changes

2021-07-06 11:17 UTC, merged