Tech CORE-366 | Encrypt the user password into the database
inspr/core-legacy pull request #93
Opened 2021-07-09 15:38 UTC by luiz-couto

# Description

Kind: Tech Pendency

Section: UIDP client

Summary:
Now all users (including admin) are being saved with encrypted passwords. Password match checks have been updated as well.

## Changelog

* Password encryption when creating user 
* Password encryption when initializing admin user
* Passord verifycation when trying to delete/update/create a new user now uses the hashed password and bcrypt function
* Updated all the tests for the functions above
* Redis install/unninstall documentation

2021-07-09 15:53 UTC, franciscobonand requested changes
Remember to update `CHANGELOG.md`. Also I registered the redis install doc in our Confluence's Useful Guides, so you can remove it from here.

2021-07-09 15:53 UTC, franciscobonand commented on cmd/uid_provider/client/client.go
> +		Password:    string(hashedPwd),
Is there a reason to store the password as a string instead of a byte array?

2021-07-09 15:53 UTC, franciscobonand commented on cmd/uid_provider/client/client.go
> +	newUser.Password = string(hashedPwd)
Same string-byte array thing here

2021-07-09 15:53 UTC, franciscobonand commented on cmd/uid_provider/client/client.go
> +	user.Password = string(hashedPwd)
Same string-byte array thing here

2021-07-09 16:38 UTC, nicholaspcr approved these changes

2021-07-09 16:41 UTC, lucasABLima approved these changes

2021-07-12 12:15 UTC, franciscobonand approved these changes

2021-07-12 12:26 UTC, merged