Tech/core 491
inspr/core-legacy pull request #95
Opened 2021-07-12 12:43 UTC by nicholaspcr

# Description

Kind: tech dep

Section: uidp/inprov

Summary: improve description of the cli commands in `inprov` and add loggers to the uidp handlers

## Changelog

> List the main points of change

## Pay attention to

> Important parts of the code that require special attention

2021-07-12 12:58 UTC, LucasStarlingdePaulaSalles requested changes

2021-07-12 12:58 UTC, LucasStarlingdePaulaSalles commented on CHANGELOG.md
> +
Missing --- at the end here

2021-07-12 12:58 UTC, LucasStarlingdePaulaSalles commented on cmd/uid_provider/api/controller/routes.go
> +	logger.Debug("initializing Insprd server routes")
uidp server routes

2021-07-12 12:58 UTC, LucasStarlingdePaulaSalles commented on cmd/uid_provider/api/handlers/handler.go
> +		logger.Info("deleting a new user")
deleting an user
deleting new user sounds counter intuitive

2021-07-12 12:58 UTC, LucasStarlingdePaulaSalles commented on cmd/uid_provider/api/handlers/handler.go
> +		logger.Info("updating a new user")
updating an user
same here

2021-07-12 15:20 UTC, LucasStarlingdePaulaSalles approved these changes

2021-07-13 13:01 UTC, luiz-couto approved these changes

2021-07-13 14:08 UTC, merged